### ISSUE TITLE
time to accept review email box wants 48hrs in weeks

### ISSUE THREAD

**Issue by srees95** [NSAMR/uk.ac.nsamr.journal#109]

**Comment by DeckOfPandas** [comment]
Progress: text is displayed correctly
Still need to alter the function that handles the form's content as it expects a week, but this is easy

if (isset($reviewAssignment) && $reviewAssignment->getDueDate() != null) {
	$reviewDueDate = strftime(Config::getVar('general', 'date_format_short'), strtotime($reviewAssignment->getDueDate()));
} else {
	$numWeeks = (int) $context->getSetting('numWeeksPerReview');
	if ($numWeeks<=0) $numWeeks=4;
	$reviewDueDate = strftime(Config::getVar('general', 'date_format_short'), strtotime('+' . $numWeeks . ' week'));
}

if (isset($reviewAssignment) && $reviewAssignment->getResponseDueDate() != null) {
	$responseDueDate = strftime(Config::getVar('general', 'date_format_short'), strtotime($reviewAssignment->getResponseDueDate()));
} else {
	$numWeeks = (int) $context->getSetting('numWeeksPerResponse');
	if ($numWeeks<=0) $numWeeks=3;
	$responseDueDate = strftime(Config::getVar('general', 'date_format_short'), strtotime('+' . $numWeeks . ' week'));
}

**Comment by DeckOfPandas** [comment]
Fixed in #236
