### ISSUE TITLE
on mobile site of machinery, logo covers breadcrumbs

### ISSUE THREAD

**Issue by srees95** [NSAMR/uk.ac.nsamr.journal#214]
![17976643_1386331811389517_669189907_o 1](https://cloud.githubusercontent.com/assets/25647928/25101546/a910926e-23ac-11e7-85ad-253c7b2934ee.jpg)

**Comment by DeckOfPandas** [comment]
Duplicate -- please close my other one about poor rendering on a mobile

**Comment by DeckOfPandas** [comment]
Duplicate issue has been closed

**Comment by DeckOfPandas** [comment]
![screen shot 2017-04-21 at 14 09 12](https://cloud.githubusercontent.com/assets/2399432/25278711/2368226a-269c-11e7-876c-6fbb5878f33f.png)

**Comment by DeckOfPandas** [comment]
When the height: line is disabled, or set to auto, the image is properly responsive.

I have hacked it for now by adding style="height:auto" to the actual php template...yeah.

**Comment by DeckOfPandas** [comment]
@lamby
?

**Comment by lamby** [comment]
I suspect that setting the `img-responsive` class on the surrounding `a` element (ie. not the `img` element) is part of the problem.
(Went to have a real look but http://www.nsamr.ac.uk/ is 500ing on me.)

**Comment by nsamr-it** [comment]
Thanks Chris. I'll try that next.

We have a live site, but it's a WIP so isn't at the "right" URL yet.
Working URLs are at the top of readme.md

<3

**Comment by DeckOfPandas** [comment]
Thanks very much Chris -- you saved me a potentially large amount of time and frustration <3

Fixed in #239

**Comment by lamby** [comment]
\o/
