### ISSUE TITLE
markers overlapping

### ISSUE THREAD

**Issue by srees95** [NSAMR/uk.ac.nsamr.journal#215]
![17976088_1386331831389515_1644903315_o](https://cloud.githubusercontent.com/assets/25647928/25101570/bb167c94-23ac-11e7-93c7-dc063176025f.jpg)

**Comment by nsamr-it** [comment]
Is that just on mobile? It actually looked okay to me on mine

I also had issues with how the bottoms don't align, so I think I'm going to
have to Actually Attend To This

**Comment by srees95** [comment]
adding    space=20 after each box fixes it, but it's setting off my 'helen wouldn't approve' alarm... @DeckOfPandas

**Comment by DeckOfPandas** [comment]
Fixed :)
