### ISSUE TITLE
flavicon for wrapper

### ISSUE THREAD

**Issue by srees95** [NSAMR/uk.ac.nsamr.journal#216]

**Comment by DeckOfPandas** [comment]
fLavicon eh?

**Comment by srees95** [comment]
JSAMR favicon? better one?
![jsamr-favicon-90](https://cloud.githubusercontent.com/assets/25647928/25107948/527c670c-23ca-11e7-91b0-3268c194afd7.png)

**Comment by DeckOfPandas** [comment]
This needs to be updated in journal admin section (wrapper site is now dead!!!!!!!!!!!!)

Can you do @srees95 ?

**Comment by srees95** [comment]
replaced with 'S' in journal admin
