### ISSUE TITLE
accordion wrapping 

### ISSUE THREAD

**Issue by srees95** [NSAMR/uk.ac.nsamr.journal#218]
![17976317_1386341958055169_1153422167_o](https://cloud.githubusercontent.com/assets/25647928/25101994/5f2bc798-23ae-11e7-848a-d80551f89bda.jpg)

**Comment by nsamr-it** [comment]
Don't include the link -- do it like...
The text of the licence can be viewed <a href="whatever">here</a>
I think that's more standard <3

**Comment by srees95** [comment]
corrected in pull request
