### ISSUE TITLE
accordion title not really legible when section open

### ISSUE THREAD

**Issue by srees95** [NSAMR/uk.ac.nsamr.journal#220]
![17976317_1386341958055169_1153422167_o](https://cloud.githubusercontent.com/assets/25647928/25102044/8f8c192e-23ae-11e7-80f2-e5bf8ef6256a.jpg)

**Comment by nsamr-it** [comment]
One for you @sress?
_accordions.scss
BUT you have to rebuild the style.css file after doing that -- see
instructions in README for NSAMR's other repo
You have to use a thing called compass to "watch" the Sass for changes,
then compile the css

**Comment by DeckOfPandas** [comment]
pinging you @srees95

**Comment by srees95** [comment]
it's a weird function of the mobile site, clicking once to open activates the hover status of the 'button'. So Either they don't change colour when you hover on browser, or mobile users suck it up? @DeckOfPandas

**Comment by nsamr-it** [comment]
I think that might actually just be how hovers work in mobile devices, as
there (obviously) isn't a mouse.

I agree that the text turns illegible though, so let's change the colour
not the behaviour (?)

**Comment by srees95** [comment]
good plan, i will attempt the css tomorrow when awake !

**Comment by nsamr-it** [comment]
:partyparrot:

**Comment by srees95** [comment]
not an issue with most recent deploy
