### ISSUE TITLE
Competing interests for reviewers

### ISSUE THREAD

**Issue by DeckOfPandas** [NSAMR/uk.ac.nsamr.journal#232]
When reviewers click through to accept a review request, do we need them to:
1. Agree to a statement that we provide
    and/or
2. Detail any conflicts in a free text box,

OR
3. Something else, e.g. nothing?

Labelled as "essential" because deciding is, even if implementing isn't.

**Comment by srees95** [comment]
we do need a statement of no conflict, but we need to decide what info we're going to give them before they decide, if it's double blind then it'll be difficult for them to say if there's a conflict even if their best bud submitted it.
maybe just a statement that says they are not aware that this work was done by soemone they know and they are not aware of any reason they shouldn't de the review? @mhvbyrne @DeckOfPandas

**Comment by DeckOfPandas** [comment]
Sounds sensible

After all, there is by definition no personal conflict if the author is truly anonymous

They probably also need to promise they don't have any academic, commercial or personal interest in whether or not the article is published ???

**Comment by srees95** [comment]
defo, sounds good

**Comment by DeckOfPandas** [comment]
@Kanshaa @godwintong @srees95 @mhvbyrne Are statements covering this already in the Author Guide? If so, do we want to pull anything out and present it during the Submission process?

I recognise that I could in theory sort this out myself, but I'm asking for someone to Just Tell Me What To Do in the interests of accuracy (and my critical path)

**Comment by mhvbyrne** [comment]
Hi Helen

Difficult to say because it's all going to be double blinded.

There was a statement in the peer review documents saying they must not
review something if it is from their institution.
But that was written for when it wasn't double blinded.

I'm in hospital now but can send it to you later

Kind regards
Matt

**Comment by srees95** [comment]
complete
