### ISSUE TITLE
Link to files in Reviewer Guidelines box

### ISSUE THREAD

**Issue by DeckOfPandas** [NSAMR/uk.ac.nsamr.journal#233]
Currently a section called "Review Guidelines" will be displayed to reviewers when they click through to a review request. Do we want to put anything here?
e.g.
* link to the file of guidelines that have been made
* link to relevant User Guide on wrapper site
etc

Or I could remove the box entirely

**Comment by srees95** [comment]
i'd say both, they're the only relevant bits to them then, but they need to know both !

**Comment by DeckOfPandas** [comment]
That can be done through Settings --> Workflow --> Review

If you can do this @srees95, then de-assign me and Matt, and let me know when it's done so I can grab myself a fresh copy of the database

**Comment by DeckOfPandas** [comment]
Done (I think) by a combination of me and Steph
