### ISSUE TITLE
Copy and paste pages

### ISSUE THREAD

**Issue by DeckOfPandas** [NSAMR/uk.ac.nsamr.journal#259]

**Comment by DeckOfPandas** [comment]
In progress

**Comment by DeckOfPandas** [comment]
About and Contact are done
Policies to follow when I've fixed a OJS bug...

**Comment by DeckOfPandas** [comment]
Hosting is done

**Comment by DeckOfPandas** [comment]
See #276 #278 etc

**Comment by DeckOfPandas** [comment]
All done except User Guides and Policies

**Comment by DeckOfPandas** [comment]
All done except policies 
See #309

**Comment by srees95** [comment]
And submit your work, the lovely timeline isn't there

**Comment by DeckOfPandas** [comment]
Done -- will make new issue for the last one
