### ISSUE TITLE
Borked img on About Page

### ISSUE THREAD

**Issue by jaspermogg** [NSAMR/uk.ac.nsamr.journal#295]
http://www.nsamr.ac.uk/journal/journal-machinery/ojs-3.0.1/index.php/jnsamr/about

![screenshot 2017-05-04 at 22 53 36](https://cloud.githubusercontent.com/assets/1735500/25726536/9810d92e-311c-11e7-8b18-f46318504d80.png)

**Comment by DeckOfPandas** [comment]
Oh balls, many images are broken

Fucking smarty

**Comment by DeckOfPandas** [comment]
Fixed in #300
