### ISSUE TITLE
404 not found thingo 

### ISSUE THREAD

**Issue by godwintong** [NSAMR/uk.ac.nsamr.journal#296]
Pressing "Contact us" under the quick link tab brings up the 404 error page
On second look, the rest of the quick links don't seem to work either
http://www.nsamr.ac.uk/journal/journal-machinery/ojs-3.0.1/index.php/jnsamr/information/contact.php

**Comment by DeckOfPandas** [comment]
Err.... Adam you try clearing your cache? (Or test in porn mode?)

**Comment by DeckOfPandas** [comment]
Yep, pretty sure this is just caching. Thanks Godwin.
