### ISSUE TITLE
Do we need another category for letters?

### ISSUE THREAD

**Issue by DeckOfPandas** [NSAMR/uk.ac.nsamr.journal#303]
e.g. 
Code	Speciality
100	Anaesthesia / Intensive Care medicine

**Comment by DeckOfPandas** [comment]
@godwintong @mhvbyrne

**Comment by DeckOfPandas** [comment]
I mean for the part where authors choose the subject codes during submission

**Comment by godwintong** [comment]
If we put in a code for letters do we need a code for all the other categories? Like case reports, images etc.. I think either way is fine? Prolly makes things more organised if there's a code for it

**Comment by srees95** [comment]
we could just have an 'other' code, for ones that aren't standard specialties e.g. artwork, letters, personal achievements

**Comment by mhvbyrne** [comment]
The codes are designed to help us send it to the correct section editor for
review

Anything that doesn't need to be peer reviewed should go in an "other/non
peer review" box

**Comment by DeckOfPandas** [comment]
Authors select a Section to submit to. These are:
![screen shot 2017-05-05 at 15 35 11](https://cloud.githubusercontent.com/assets/2399432/25750071/8bd158dc-31a8-11e7-8a83-36e7452ad1ba.png)

We then ask them to add Subject codes here:
![screen shot 2017-05-05 at 15 36 24](https://cloud.githubusercontent.com/assets/2399432/25750134/a5a6f44c-31a8-11e7-9fc4-d7be3036beaa.png)
from this list here: 
![screen shot 2017-05-05 at 15 37 15](https://cloud.githubusercontent.com/assets/2399432/25750160/c225a4ec-31a8-11e7-9936-4affed762107.png)

Do we want people to choose subject codes for all Sections? Does it make sense for someone to code their opinion piece as "Clinical Immunology"? Should there be a "General / N/A" subject code as well?

**Comment by mhvbyrne** [comment]
Ah okay,
Looks so good!

Yes general code would be good

**Comment by DeckOfPandas** [comment]
@mhvbyrne 
Matt this is related to current Issues #374 and more, as discussed this morning. We need ONE BIG LIST of manuscript types, and ONE BIG LIST of medical codes

**Comment by DeckOfPandas** [comment]
See #432 and #433 and #428 . Closing.
