### ISSUE TITLE
All the "Other manuscript types" need to be added as journal Sections via the admin site

### ISSUE THREAD

**Issue by DeckOfPandas** [NSAMR/uk.ac.nsamr.journal#308]
Can you do this @srees95 ?

**Comment by DeckOfPandas** [comment]
Did you do this?
Some of the Sections have sneaked back in, e.g. "Research Instrument"...
http://www.nsamr.ac.uk/journal/jsamr/index.php/jnsamr/management/settings/publication

![screen shot 2017-05-05 at 14 52 41](https://cloud.githubusercontent.com/assets/2399432/25748310/88fde9c8-31a2-11e7-885a-72bebb8edce5.png)

**Comment by srees95** [comment]
nope, not me

**Comment by srees95** [comment]
manuscript types done
