### ISSUE TITLE
clicking on user guides screws wrapping of header (pic)

### ISSUE THREAD

**Issue by srees95** [NSAMR/uk.ac.nsamr.journal#314]
![wrapping issue](https://cloud.githubusercontent.com/assets/25647928/25744977/ada0aa1c-3194-11e7-8f31-9dd1cfbcd470.png)

**Comment by srees95** [comment]
AND stops header being responsive.
not an issue when you use the drop down inside 'contribute' to go to user guides etc, only when you click on 'contribute'

**Comment by srees95** [comment]
duplicate

**Comment by DeckOfPandas** [comment]
...wow

Could you try loading the site in porn mode? It might be a caching thing, because I don't see that...

**Comment by srees95** [comment]
not a thing in porn mode
I love caches *sigh*
