### ISSUE TITLE
journal thumbnail needs replacing with jsamr not jnsamr

### ISSUE THREAD

**Issue by srees95** [NSAMR/uk.ac.nsamr.journal#317]
i don't have access to the google drive file, so only have the clear background image rather than blue

**Comment by DeckOfPandas** [comment]
@rmlundin Sorry to pester you with this again... Could you upload the gorgeous new logo and favicon in this thread?

**Comment by srees95** [comment]
![short](https://cloud.githubusercontent.com/assets/25647928/25749957/342a84d2-31a8-11e7-94d0-cd029c0b4f7c.png)
![jsamr logo wide 1200 1 6387](https://cloud.githubusercontent.com/assets/25647928/25749958/342ba40c-31a8-11e7-9ae0-783a93831d04.png)

**Comment by srees95** [comment]
we just need the blue JSAMR, thanks @rmlundin

**Comment by DeckOfPandas** [comment]
This looks to me like it has been done? @srees95 ? Close this Issue if you agree...

**Comment by DeckOfPandas** [comment]
I think this has been done
