### ISSUE TITLE
author name becomes part of uploaded file name, not double blind !

### ISSUE THREAD

**Issue by srees95** [NSAMR/uk.ac.nsamr.journal#319]

**Comment by DeckOfPandas** [comment]
There's a setting for this somewhere... I know that's not that helpful, but I definitely put in a thing that renames uploaded files to something like Author,Author_Title.pdf

**Comment by DeckOfPandas** [comment]
Have you tried looking at this as a non-admin? I think perhaps that Journal Editors (i.e. just the fiveish of us) know who everyone is, it's the the reviewer-author pairings that don't. Could you try it?

**Comment by srees95** [comment]
yep, just submitted something and the file name's me

**Comment by srees95** [comment]
it's a weird OJS thing
http://forum.pkp.sfu.ca/t/submission-track-names-of-files/30430/12

fixed, i think
