### ISSUE TITLE
manuscript guidnace asks for a title page with names of all authors etc ect #doubleblind

### ISSUE THREAD

**Issue by srees95** [NSAMR/uk.ac.nsamr.journal#321]

**Comment by srees95** [comment]
I've changed it to say that we will ask for this to be submitted once all changes have been made, and only then. 
Thank okay @mhvbyrne

**Comment by nsamr-it** [comment]
Perfect

**Comment by DeckOfPandas** [comment]
So is this sorted? If so, please close @srees95
