### ISSUE TITLE
Typo in 'Peer Review Process' in Policies

### ISSUE THREAD

**Issue by Kanshaa** [NSAMR/uk.ac.nsamr.journal#338]
http://www.nsamr.ac.uk/journal/jsamr/index.php/jnsamr/about/policies
7. The Section Editor then compiles a peer review summary and [SENDS A] decision to the author
9. If the Section Editor chooses ‘accept with minor revisions’ or ‘revise and resubmit’, the Section Editor should send the peer-review summary and deicision [DECISION] to the Author

**Comment by srees95** [comment]
done
