### ISSUE TITLE
medical codes

### ISSUE THREAD

**Issue by srees95** [NSAMR/uk.ac.nsamr.journal#374]
-medical technology
-medical humanities
-statistics

**Comment by DeckOfPandas** [comment]
@mhvbyrne If you agree the above need to be added then I'll put them in

**Comment by DeckOfPandas** [comment]
@mhvbyrne These need to be sorted now, so when you assign keywords for this round of publishing they will be consistent for the future

**Comment by DeckOfPandas** [comment]
See #432 and #433. Closing.
