### ISSUE TITLE
Homepage Minor Issues

### ISSUE THREAD

**Issue by ciarang-c** [NSAMR/uk.ac.nsamr.journal#380]
![scale issue](https://user-images.githubusercontent.com/30594062/28775302-1c166cb4-75e9-11e7-9ef9-1cac1e7ed4b6.png)

Minor scaling issue with the attached image. Also consider having the first image 'Sign-up' sit on the page for longer before flicking over to the NSAMR home image.

**Comment by DeckOfPandas** [comment]
@hmorrin I pinged you about this on Slack :)

**Comment by DeckOfPandas** [comment]
Wrong site, many other wrong, closing
@hmorrin
