### ISSUE TITLE
lost resubmission

### ISSUE THREAD

**Issue by srees95** [NSAMR/uk.ac.nsamr.journal#389]
![resubmission 1](https://user-images.githubusercontent.com/25647928/34111005-44e69166-e400-11e7-8976-c193822b27a9.png)

**Comment by srees95** [comment]
![resubmission 2](https://user-images.githubusercontent.com/25647928/34111039-5ec53146-e400-11e7-9214-88f2bcb2cc35.png)

**Comment by srees95** [comment]
same with http://journal.nsamr.ac.uk/jsamr/index.php/jnsamr/workflow/index/22/3

**Comment by DeckOfPandas** [comment]
This was resolved over slack -- the author had mashed their own file. I have backups either side showing the uploaded files were identical before and after this.
