### ISSUE TITLE
make template coversheet ?

### ISSUE THREAD

**Issue by srees95** [NSAMR/uk.ac.nsamr.journal#412]

**Comment by DeckOfPandas** [comment]
+1

Make one as simply as possible, just an .rtf file or something that users can open in any program, then add it to GitHub (new folder "submission docs") and tell them to submit it as a pdf?

**Comment by DeckOfPandas** [comment]
Continued in #416

**Comment by DeckOfPandas** [comment]
See also #416

**Comment by DeckOfPandas** [comment]
Part of #392 now
