### ISSUE TITLE
documents ending in (2) are corrupted on the site 

### ISSUE THREAD

**Issue by srees95** [NSAMR/uk.ac.nsamr.journal#415]

**Comment by DeckOfPandas** [comment]
What does this mean?
Can you check again please with a new document? 
I was looking at this yesterday and it looked okay.

Could it be that you're requesting files that aren't in the system, maybe if sandbox db had something submitted that is somehow no longer in the uploads folder?

**Comment by DeckOfPandas** [comment]
Cannot replicate
