### ISSUE TITLE
Spec for article display

### ISSUE THREAD

**Issue by DeckOfPandas** [NSAMR/uk.ac.nsamr.journal#426]
# Thumbnail cover image
* 72dpi, 595*841 px (A4 aspect ratio)

# Galley items
* PDF
* OpenDyslexic PDF
* Original submission
* Peer-review documents
* ... ???

Dates:
* Submitted: 
* Accepted: 
* Published online: 

# Title
* Font and params and color as specified, and consistent with laTeX typesetting: Open Sans, bold, letter spacing 1.05 em, line height 1.25

# Authors
* Firstname Initial Surname, e.g. Helen M Jackson
* Separated by commas
* Superscript markup for corresponding author and their email address (as image for antispam)
* Superscript markup for affiliation

# Abstract
* Heading font as per laTeX typesetting: TODO
* Text arranged via metadata: split into sections with name in bold, e.g.:

```
*Introduction*
words words words

*Methods*
words words words

etc
```

# Keywords
Above or below abstract ???

# How to Cite
* List of types: TODO

------

# Design considerations

**Comment by DeckOfPandas** [comment]
@mhvbyrne This is what I mean by a spec. Please add the details I don't yet have!

**Comment by mhvbyrne** [comment]
**GALLEY**
Figures (with captions) - is this worthwhile or is it going to be a massive faff?
Tables (with captions)
References - is this worthwhile or is it going to be a massive faff?
Dataset

**AUTHORS**
In the pdf file i've used the following:
Superscript markup for corresponding author (using alpha) and their email address (as image for antispam)
Superscript markup for affiliation (using numbered)
Superscript markup for joint first authorship (using *)

**Keywords**
Above abstract or to the left underneath all galley stuff

**Comment by mhvbyrne** [comment]
How to do thumbnail: go to preview, export front page as PNG

**Comment by DeckOfPandas** [comment]
References can be done through the system. actually, then printed on the article view page. Let's investigate together today, as I think this would be really worthwile.

**Comment by DeckOfPandas** [comment]
More on thumbnail: PNG aspect ratio as per a4 please, 72dpi

**Comment by DeckOfPandas** [comment]
All others done in current preview draft, other than affiliations all as a list rather than with superscript

**Comment by DeckOfPandas** [comment]
## Galley items
* PDF
* OpenDyslexic PDF
* Review Process
* Raw Data
* Data Analysis
* Transcripts
* Hi-res Images

Could be many things

Might not be too many more than those (?)

**Comment by srees95** [comment]
what will be in raw data/analysis/transcripts/high res images
Everything that would be in the appendix of a dissertation?

**Comment by mhvbyrne** [comment]
Poster
