### ISSUE TITLE
Spec for end matter for each article

### ISSUE THREAD

**Issue by DeckOfPandas** [NSAMR/uk.ac.nsamr.journal#430]
Continued from #414

**Comment by DeckOfPandas** [comment]
Example:
![screenshot_20181108-220656](https://user-images.githubusercontent.com/2399432/49155298-8324fb80-f312-11e8-98ab-f04c4cbdbb35.png)

Preferably in good English and without typos.

Make a new .tex file, and \include it at the end of each article, before the References ???

**Comment by DeckOfPandas** [comment]
Related to canonical list of documents authors should submit with any manuscript, all in #392

**Comment by mhvbyrne** [comment]
case reports, and editorials will need different end matter, the rest will be the same

**Comment by DeckOfPandas** [comment]
Can you upload what you have so far here please, @mhvbyrne ? Otherwise brain will melt futher

**Comment by mhvbyrne** [comment]
Should be on all articles I’ve sent you
