### ISSUE TITLE
Spec for article codes

### ISSUE THREAD

**Issue by DeckOfPandas** [NSAMR/uk.ac.nsamr.journal#432]
Continuing from #374 and more. (Actually do look at that issue to get required additions to current list.)

This is separate to keywords, which will all come from mesh as specified by Matt

**Comment by DeckOfPandas** [comment]
See #303 too

**Comment by DeckOfPandas** [comment]
Full list as per current, with these added:
* Medical technology
* Medical humanities
* Statistics

**Comment by DeckOfPandas** [comment]
Could someone create the full list in alphabetical order with number codes (see website docs for current list) and write it here, then I can be super clear on it for adding to the website in the future?

**Comment by mhvbyrne** [comment]
https://docs.google.com/spreadsheets/d/1R7MKSy4gG2QEbpva57YLg8Jsi--a3AiVyw9whQ7E6vs/edit#gid=0
