### ISSUE TITLE
Final details and author signoff for final 2018 conference abstract

### ISSUE THREAD

**Issue by DeckOfPandas** [NSAMR/uk.ac.nsamr.journal#482]
Steph: I need:
* Corresponding email address 
* Full author names

Then I will update the draft

Then can you get author signoff?

@srees95

**Comment by srees95** [comment]
yep, email sent, and I've told her that we'll be sending it to her for the final go ahead once we have those

**Comment by DeckOfPandas** [comment]
Duplicate of #487 , closing
