### ISSUE TITLE
Errors in Volume 1, Issue 1

### ISSUE THREAD

**Issue by mhvbyrne** [NSAMR/uk.ac.nsamr.journal#488]
EDITORS Page
#486 
- Ciaran and Akanksha have graduated ?Update bios (contacted by steph)
- update of Stephs bio
- Helen's bio is too long

**Comment by mhvbyrne** [comment]
Not peer reviewed rather than Not peer-reviewed in non conference pieces
Page number p. 1 instead of p.1 in non conference pieces

**Comment by mhvbyrne** [comment]
PARKIN ABSTRACT - unknown affiliations for all authors and corresponding email address

**Comment by mhvbyrne** [comment]
Unable to upload the correct front page to Issue 1, it displays the old front page

**Comment by mhvbyrne** [comment]
NOT RESOLVED:
**Krishnan (review) currently incorrectly under Original research section as no Reviews section or broader group for review and original research** Needs a Reviews Section

RESOLVED:
_Krishnan has green boxes round it: \hypersetup{hidelinks}
TITLE on system: remove colon, and capitalise T of the in the subheading_

**Comment by mhvbyrne** [comment]
ISSUE SUMMARY
Explain cover image choice in summary
Change name of article to: Issue Summary: Volume 1, Issue 1

**Comment by mhvbyrne** [comment]
Green keywords and orange galley buttons - need to change to one or the other
White text above keywords
![screen shot 2018-12-28 at 14 23 56](https://user-images.githubusercontent.com/25647905/50518313-fc984100-0aac-11e9-9137-d648cf8ab4ec.png)

**Comment by mhvbyrne** [comment]
Krishnan has green boxes round it: \hypersetup{hidelinks}

**Comment by mhvbyrne** [comment]
HASHEMI - in the abstract and first paragraph KCL CARS is written out in full as 'clinical academic and research society' but it should be 'clinical and academic research society'

**Comment by mhvbyrne** [comment]
Name of journal in system needed to change to National student...

The cite as is incorrect
![screen shot 2018-12-28 at 14 37 46](https://user-images.githubusercontent.com/25647905/50518569-387fd600-0aae-11e9-8458-a5994bc94963.png)

**Comment by mhvbyrne** [comment]
EDITORIAL
Change name to: Focus and Scope of the Journal of the National Student Association of Medical Research

**Comment by mhvbyrne** [comment]
?add united kingdom after author affiliations on website

**Comment by mhvbyrne** [comment]
?remove month from 2018 as we will be publishing two issues in December otherwise

**Comment by DeckOfPandas** [comment]
Re: keywords:
I think visual balance is nicer with a second contrast colour, so galley links in one and keywords in another. I think @srees95 agreed with me, if not on exactly this colour then sure, but I'm almost certain she agreed to the need for another spot colour.

**Comment by DeckOfPandas** [comment]
Everyone on the editorial team should probably read your editorial @mhvbyrne , you know, transparency re: what they're putting their names on n ting

**Comment by mhvbyrne** [comment]
> Everyone on the editorial team should probably read your editorial @mhvbyrne , you know, transparency re: what they're putting their names on n ting

I've posted it in the JSAMR chat previously

> Re: keywords:
> I think visual balance is nicer with a second contrast colour, so galley links in one and keywords in another. I think @srees95 agreed with me, if not on exactly this colour then sure, but I'm almost certain she agreed to the need for another spot colour.

Yeah that's fine I'm just not a fan of orange and green combo, orange and pink? two shades of orange... grey ;)
