### ISSUE TITLE
HOWTO: Production

### ISSUE THREAD

**Issue by mhvbyrne** [NSAMR/uk.ac.nsamr.journal#490]
1. If there is no submission already (e.g. conference abstracts, editorials) you will need to make a ``New Submission''. If there is already a submission (e.g. reviews, original research, case reports etc) you will need to use this.
1. For new submissions:
  1. Select the correct section, tick all of the tick boxes, and click save and continue.
  1. Upload the article components under the correct headings (uploading PDFs under ``article text'' will be the one you use pretty much all of the time)
  1. Enter the metadata from the LaTeX document, you will need to remove all LaTeX code. The common LaTeX code that will need to be removed is \mbox{WORD} from the title (this prevents hyphenation of that word at the end of a line) and special symbols in the abstract (these will need to be replaced with ordinary text).
  1. Copy and paste the title - remove any code
  1. Copy and paste the abstract - remove any code, make introduction, methods, results, and discussion bold and put them on the same line as the section they relate to (e.g. **introduction**: text), each section should be separated by a blank line.
  1. Remove yourself as an author, and enter the correct authors and their affiliations
  1. You are required to enter the email address for all authors. Only the corresponding authors email address will be displayed. You can use journal@nsamr.ac.uk for the rest.
  1. If you need to change the order of the authors, you can click the ``Order'' link, which will allow you to drag the authors into the correct order.
  1. Copy and paste the key words and separate them by a comma to make them into separate keywords.
  1. Finish submission (there's a bug here where it won't take you to the next step, just click onto submissions and find it again)
1. Click onto the submission and assign yourself as an editor
1. Refresh the page, and send to copy editing (click that you do not want to send an email to the author), then send to production (again click that you don't want to send an email to the author).
1. Click on Metadata, now you can add the cover image (copy of the first page as a PNG file 72dpi), click save.
1. Stay in the metadata pop up, and click on identifiers (at the top) and enter the URL for that submission. This will be in the format: Year-volume-issue-authorsurname. e.g. 2018-1-1-byrne. For multiple submissions by the same author in the same issue add the number afterwards. e.g. 2018-1-1-byrne-2. Do not add -1 to the first submission. Click save and exit the pop up.
1. Scroll down to Galleys, click add Galley. Label the galley (see complete galley list: PDF for the main text, Poster for posters etc), upload the typeset file.
1. Click Schedule for production.
  1. Schedule for production in the correct future issue, when the issue will be published, enter the page number in the form x-y for multiple pages, x for single.
  1. Click schedule for production again and change the date published to the agreed date for the publication of the issue.
  1. The Permissions for the submission should automatically be attached.
1. Every time a subsequent change is made to the submission after it has been scheduled for publication, you will need to click schedule for production again.

**Comment by DeckOfPandas** [comment]
A few addition and (hopefully) clarifications

**Comment by DeckOfPandas** [comment]
Balls, made (extensive and time-consuming, sigh) suggestions to the wrong wall of text... Will return to this doc soon.
