### ISSUE TITLE
Character case for page numbers in front matter

### ISSUE THREAD

**Issue by DeckOfPandas** [NSAMR/uk.ac.nsamr.journal#493]
Currently II, III, IV, V, VI etc

I was going to claim this is more common, but actually i don't know; either way, I strongly prefer i, ii, iii, iv etc, because then my eye can tell easily that it's not supposed to be reading weird-fonted numbers rather than Roman numerals.

@srees95 @mhvbyrne 
Question: are you going to name the front cover page i, or nothing? (My preference is for the latter, since I wasn't asked, you know, standard Helen)

**Comment by mhvbyrne** [comment]
Latex automatically capitalises
Front cover is page 0

**Comment by mhvbyrne** [comment]
changed to lower case
