### ISSUE TITLE
FRONT MATTER THOUGHTS AND ISSUES

### ISSUE THREAD

**Issue by DeckOfPandas** [NSAMR/uk.ac.nsamr.journal#497]
1. Entries in table of contents all give "Volume 1 Issue 1" as a subtitle, which is visually strange
1. Do these need keywords, and citation dropdowns? Discussion in #494 
1. "Editors" or "Editorial Team"? For page title and also running header
1. We don't need page numbers on both sides of the page footer
1. Better title for @mhvbyrne 's summary article
1. Is the summary article finished...? Will hold fire if not.

**Comment by mhvbyrne** [comment]
Page numbers on both sides so that readers know what the page bounds are for multi page articles
