### ISSUE TITLE
New submissions process -- Put self-selected topic codes in "Notes to editor"

### ISSUE THREAD

**Issue by DeckOfPandas** [NSAMR/uk.ac.nsamr.journal#81]

**Comment by DeckOfPandas** [comment]
"Suggest some topic codes <link>"
In authorguide.php

**Comment by DeckOfPandas** [comment]
@srees95 @mhvbyrne 
Sorry if I've missed something, are we going with getting authors to suggest topic codes, or keywords, or both, or neither?

I understand that we want extra information (possibly the above) included in the "Comments for the Editor" box in the attached picture, but please can someone tell me what to write that we want people to include in the "Comments..." box

**Comment by mhvbyrne** [comment]
Hi Helen,

Yes I think author suggesting topic code and 3-5 key words will help us

Kind regards
Matt

**Comment by DeckOfPandas** [comment]
Done in #326
