### ISSUE TITLE
Article identifiers -- e.g. volume-issue-page number

### ISSUE THREAD

**Issue by DeckOfPandas** [NSAMR/uk.ac.nsamr.journal#96]
1-1-132-137

**Comment by mhvbyrne** [comment]
I will organise this over summer for our first issue

**Comment by DeckOfPandas** [comment]
This issue means that we need an internal way of referring to our publications, both throughout the tech stack (which will be reflected in tidy URLs), and also to specify how to cite our publications in various different citation styles.

e.g. An article authored by Matt in the first ever journal issue we make could be:
M. H. V. Byrne. 2017. Title. J Stu Assoc Med Res.1:1-11. doi:xxx
M. H. V. Byrne. 2017. Title. J Stu Assoc Med Res.1(1):1-11. doi:xxx
Or whatever.

One idea we had previously was that each year is aa Volume number, and Issues reset to 1 each year. Another idea is just successive Issue numbers regardless of the year.

Can everyone comment please?

@NSAMR/journal-team

**Comment by godwintong** [comment]
I have seen journals doing both styles but I thibj each year to be a volume number would be tidier? Not sure if it's more work on the tech side

**Comment by DeckOfPandas** [comment]
Thanks Godwin.

Neither is any more work -- it's simply that not having a system is a horribly large amount of work. (As a sidenote, having a system and then changing it is hard, but less hard).

**Comment by DeckOfPandas** [comment]
As of phonecall this morning, @mhvbyrne and I agree with @godwintong above that vol year will be awes

**Comment by mhvbyrne** [comment]
year-vol-issue-surname
